### ISSUE TITLE
リダイレクトで書き込み権限がない時の終了ステータス

### ISSUE THREAD

**Issue by yshima42** [hyoshie/minishell#2]
シングルプロセスの時に終了ステータスの値が違う

**Comment by hyoshie** [comment]
#5 今この作業してるので、こちらで担当します。もし終わっていたら、現在のmainブランチの仕様に合わせてください。

**Comment by yshima42** [comment]
> #5 今この作業してるので、こちらで担当します。もし終わっていたら、現在のmainブランチの仕様に合わせてください。

ありがとうございます。まだ対応していないので全力で作業お願いします。
